### ISSUE TITLE
Error on finish launch w/o any answer

### ISSUE THREAD

**Issue by e-olga** [avarabyeu/rpquiz#1]
Steps:
1. User sends "start", the first question appears.
2. User does not answer the question
3. User sends "stop", the error appears
![image](https://user-images.githubusercontent.com/22497746/44918931-dbb12080-ad44-11e8-8e3a-859b9e892c90.png)

**Comment by avarabyeu** [comment]
@e-olga Do you think we need to finish launch in RP in this case? Will it make sense to interrupt it?

**Comment by e-olga** [comment]
@avarabyeu, I suppose, it should work the same as Force finish functionality in RP. So, launch gets status STOPPED, item gets status INTERRUPTED.

**Comment by VolhaKarenko** [comment]
Verified
