### ISSUE TITLE
Grammatical mistake in greeting 

### ISSUE THREAD

**Issue by VolhaKarenko** [avarabyeu/rpquiz#15]
1) Start a quiz

**Expected result:** Hi ! We are starting **a** new quiz!

**Actual result:** Hi ! We are starting new quiz!

![chatbot_greeting](https://user-images.githubusercontent.com/42797492/45292666-92a85b80-b4fe-11e8-8018-070ae6b14863.png)

**Comment by pbortnik** [comment]
Fixed
