### ISSUE TITLE
Launch should have standard RP structure

### ISSUE THREAD

**Issue by e-olga** [avarabyeu/rpquiz#5]
The reported launch should have structure
Suite>Test>Step

Please add one more level (SUITE) in reported launch

**Comment by e-olga** [comment]
Andrei, please report the last element (the question itself) with "type":"STEP". So, navigation via statistics will lead to STEP view and allow to see and use all functionalities of this page.
Thanks,
Olga

**Comment by VolhaKarenko** [comment]
Verified
