### ISSUE TITLE
Launch is in progress but the session in Telegram is not found

### ISSUE THREAD

**Issue by e-olga** [avarabyeu/rpquiz#7]
Steps:
1. Start the quiz
2. Verify the launch is started
3. Do not finish the quiz (leave it in progress)
4. Some hours later continue the quiz by selecting an answer.

*Expected:*
It possible to continue the quiz.

*Acual:*
The error in Telegram is 'Sorry, error has occured: session for user <userId> not found'
launch in RP: Quiz by Olga Ermolovich #16

**Comment by VolhaKarenko** [comment]
Verified
