### ISSUE TITLE
Launch owner should have value of username or profile name

### ISSUE THREAD

**Issue by e-olga** [avarabyeu/rpquiz#8]
As for now, the Telegram's username is added to launch name
![image](https://user-images.githubusercontent.com/22497746/45208069-64bedf00-b292-11e8-8524-14052ec86fec.png)
Expected: User is shown as an owner of a launch

**Comment by avarabyeu** [comment]
@e-olga that's expected. Since bot uses special internal account to report data. We definitely don't want to implement OAuth-based authorization between bot and report portal
