### ISSUE TITLE
Launch is not have defined name and tags

### ISSUE THREAD

**Issue by e-olga** [avarabyeu/rpquiz#9]
Expected: 
![image](https://user-images.githubusercontent.com/22497746/45208169-a2236c80-b292-11e8-886f-99ccd137ee67.png)
Actual:
![image](https://user-images.githubusercontent.com/22497746/45208189-acde0180-b292-11e8-8305-0da357bb5641.png)

**Comment by avarabyeu** [comment]
goes to @pbortnik. BTW, OS version, mobile operator and other - secure info and not exposed to the telegram client. 
Here is message object representation:
https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/types.go#L132

**Comment by pbortnik** [comment]
Name is updated in the next format: SEC-RP-quiz: login
